In [1]:
#importing libraries
import os
import pandas as pd
import numpy as np
os.chdir('D:\Engineering Design\Term 2\ML\Assignment-1')

In [2]:
# importing the dataset
test=pd.read_csv('mnist_test.csv')
train=pd.read_csv('mnist_train.csv')

In [3]:
#Analysing the dataset
test.shape

(10000, 785)

In [4]:
train.shape

(60000, 785)

In [5]:
#Splitting train and test set- dependent and independent variables
y_test=test.iloc[:,0]
y_train=train.iloc[:,0]

In [6]:
y_test

0       7
1       2
2       1
3       0
4       4
       ..
9995    2
9996    3
9997    4
9998    5
9999    6
Name: label, Length: 10000, dtype: int64

In [7]:
y_train

0        5
1        0
2        4
3        1
4        9
        ..
59995    8
59996    3
59997    5
59998    6
59999    8
Name: label, Length: 60000, dtype: int64

In [8]:
x_test=test.iloc[:,1:]
x_train=train.iloc[:,1:]

In [9]:
x3=x_train.copy()
x3=np.asarray(x3)

In [10]:
x3.shape

(60000, 784)

In [11]:
x4=x_test.copy()
x4=np.asarray(x4)

In [12]:
x4.shape

(10000, 784)

In [13]:
x_train = np.asarray(x_train)
x_test =np.asarray(x_test)

In [14]:
#One Hot Encoding Label column

In [15]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()
y_train=np.asarray(y_train)
y_train=y_train.reshape(-1,1)
y_test=np.asarray(y_test)
y_test=y_test.reshape(-1,1)

In [16]:
y_train.shape

(60000, 1)

In [17]:
y_test.shape

(10000, 1)

In [18]:
y_test=ohe.fit_transform(y_test).toarray()
y_train=ohe.fit_transform(y_train).toarray()

C:\Users\Raksha\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Raksha\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you 

In [19]:
y_test

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [20]:
#Creating copies
y3=np.copy(y_train)
y3=np.asarray(y3)
y4=np.copy(y_test)
y4=np.asarray(y4)

In [21]:
y3.shape

(60000, 10)

In [22]:
#Decision Tree - Classification 

In [23]:
from sklearn.model_selection import GridSearchCV, cross_val_score

In [24]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()

In [25]:
dt2=DecisionTreeClassifier()
c=dt2.fit(x3,y3)

In [26]:
y_pred=c.predict(x_test)

In [28]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_test,y_pred)

In [29]:
acc

0.8773

In [41]:
criterion=['gini','entropy']
max_depth=range(1,25)

In [42]:
parameters=dict(criterion=criterion, max_depth=max_depth)

In [43]:
gs= GridSearchCV(dt,parameters,cv=5, n_jobs=-1)

In [44]:
gs.fit(x_train,y_train)

GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=DecisionTreeClassifier(class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features=None,
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              presort=False, random_state=None,
                                              splitter='best'),
             iid='warn', n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': range(1, 25)},
             pre_dispatch=

In [45]:
# View The Best Parameters
print('Best Criterion:', gs.best_estimator_.get_params()['criterion'])
print('Best max_depth:', gs.best_estimator_.get_params()['max_depth'])


Best Criterion: entropy
Best max_depth: 18


In [47]:
dt3=DecisionTreeClassifier(criterion='entropy', max_depth=18)

In [48]:
c2=dt3.fit(x_train,y_train)

In [49]:
y_pre=c2.predict(x_test)

In [50]:
ac=accuracy_score(y_test,y_pre)

In [51]:
ac

0.8833

In [54]:
#Increase in accuracy score after hyper parameter tuning

In [55]:
ac-acc

0.006000000000000005

In [56]:
#Accuracy- Accuracy score
from sklearn.metrics import classification_report
cl1=classification_report(y_test,y_pre)
cl1

C:\Users\Raksha\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels.
  'precision', 'predicted', average, warn_for)


'              precision    recall  f1-score   support\n\n           0       0.94      0.94      0.94       980\n           1       0.97      0.97      0.97      1135\n           2       0.87      0.85      0.86      1032\n           3       0.82      0.86      0.84      1010\n           4       0.89      0.87      0.88       982\n           5       0.83      0.85      0.84       892\n           6       0.91      0.89      0.90       958\n           7       0.90      0.89      0.90      1028\n           8       0.84      0.83      0.84       974\n           9       0.86      0.86      0.86      1009\n\n   micro avg       0.88      0.88      0.88     10000\n   macro avg       0.88      0.88      0.88     10000\nweighted avg       0.88      0.88      0.88     10000\n samples avg       0.88      0.88      0.88     10000\n'

In [57]:
#decoding one hot encoder
decode=y_pre.dot(ohe.active_features_).astype(int)
decode2=y_test.dot(ohe.active_features_).astype(int)

C:\Users\Raksha\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:100: DeprecationWarning: The ``active_features_`` attribute was deprecated in version 0.20 and will be removed 0.22.
  warnings.warn(msg, category=DeprecationWarning)
C:\Users\Raksha\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:100: DeprecationWarning: The ``active_features_`` attribute was deprecated in version 0.20 and will be removed 0.22.
  warnings.warn(msg, category=DeprecationWarning)


In [58]:
decode

array([7, 6, 1, ..., 4, 5, 6])

In [59]:
decode2

array([7, 2, 1, ..., 4, 5, 6])

In [60]:
from sklearn.metrics import confusion_matrix
confusion_matrix(decode2, decode)

array([[ 919,    1,   10,    6,    4,   11,   16,    2,    6,    5],
       [   0, 1100,    2,   10,    1,    6,    4,    2,    7,    3],
       [  10,    6,  877,   31,   11,    7,   16,   35,   31,    8],
       [   5,    0,   17,  873,    4,   51,    8,   15,   22,   15],
       [   6,    3,   13,   10,  852,    7,    8,   10,   18,   55],
       [  11,    5,    9,   40,    9,  760,   14,    6,   19,   19],
       [  12,    3,   13,    5,   19,   30,  851,    6,   16,    3],
       [   5,    6,   30,   20,    9,    7,    1,  920,   11,   19],
       [   9,    3,   29,   45,   13,   23,   14,    6,  813,   19],
       [   5,    2,    9,   23,   39,   12,    7,   18,   26,  868]],
      dtype=int64)

On comparing the accuracies of two model, they are performing equally well